project:
  type: website

website:
  title: "Lee Qi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: collab.qmd
        text: Collaboration
    tools:
      - icon: envelope
        href: mailto:leeqi@uw.edu
      - icon: github
        href: https://github.com/lee-qi
      - icon: google
        href: https://scholar.google.com/citations?user=BvH69aQAAAAJ&hl=en&oi=ao

format:
  html:
    theme:
      dark: [simplex, theme/custom.scss, theme/dark.scss]
      light: [simplex, theme/custom.scss]
    css: styles.css
    toc: false



